import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Bidder UI Theme adaptation
        background: "#F9F8F3",
        "primary-container": "#FFE0B2",
        "surface-tint": "#f67904",
        "inverse-surface": "#2d3135",
        "surface-dim": "#D5D2CB",
        "inverse-primary": "#FFCC80",
        "on-tertiary-fixed-variant": "#842225",
        "secondary-container": "#DCEDC8",
        "primary-fixed": "#FFE0B2",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eef1f6",
        "on-tertiary-fixed": "#410005",
        "on-primary-fixed": "#E65100",
        "primary-fixed-dim": "#FFCC80",
        "on-secondary-fixed": "#1B5E20",
        "surface-container-high": "#E9E6DF",
        "tertiary-fixed": "#ffdad7",
        tertiary: "#a43a3a",
        "on-surface": "#181c20",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#DCEDC8",
        surface: "#ffffff",
        "outline-variant": "#d3c1cf",
        error: "#ba1a1a",
        "surface-container-highest": "#E3E0D9",
        "surface-bright": "#F9F8F3",
        primary: "#f67904",
        "surface-container": "#EFECE5",
        "on-error-container": "#93000a",
        "on-surface-variant": "#4f434e",
        "on-tertiary-container": "#711419",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#F57C00",
        "on-background": "#181c20",
        "surface-variant": "#F4F1EB",
        secondary: "#178630",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#C5E1A5",
        "on-secondary-container": "#1B5E20",
        "tertiary-container": "#fc7c78",
        outline: "#81737f",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#33691E",
        "on-primary-container": "#E65100",
        "tertiary-fixed-dim": "#ffb3af",
        "surface-container-low": "#F4F1EB",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        "container-margin": "24px",
        xs: "4px",
        sm: "8px",
        base: "4px",
        gutter: "20px",
        xl: "32px",
        md: "16px",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
