import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color System from design reference
        background: "#f8f9ff",
        "primary-container": "#10b981",
        "surface-tint": "#006c49",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "inverse-primary": "#4edea3",
        "on-tertiary-fixed-variant": "#842225",
        "secondary-container": "#fd761a",
        "primary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed": "#410005",
        "on-primary-fixed": "#002113",
        "primary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#341100",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#ffdad7",
        tertiary: "#a43a3a",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdbca",
        surface: "#f8f9ff",
        "outline-variant": "#bbcabf",
        error: "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        primary: "#006c49",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3c4a42",
        "on-tertiary-container": "#711419",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#005236",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        secondary: "#9d4300",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ffb690",
        "on-secondary-container": "#5c2400",
        "tertiary-container": "#fc7c78",
        outline: "#6c7a71",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#783200",
        "on-primary-container": "#00422b",
        "tertiary-fixed-dim": "#ffb3af",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        "container-margin": "24px",
        xs: "4px",
        sm: "8px",
        base: "4px",
        gutter: "20px",
        xl: "32px",
        md: "16px",
      },
      fontFamily: {
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "title-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
